name: Test workflow

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.6, 2.7]
        rails: ['~> 4.1', '~> 5.2', '~> 6.0']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Setup wkhtmltopdf
      run: |
        sudo apt-get -qq -y install fontconfig libxrender1
        wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
        sudo apt-get install ./wkhtmltox_0.12.5-1.xenial_amd64.deb

    - name: Run tests
      run: bundle exec rake
